how to listen when animation ends? #36
takahirom/PreLollipopTransition pull request #40
Opened 2016-10-08 09:17 UTC by lovejjfg

add enterListener and exitListener in `Transition` !

        exitTransition = ActivityTransition
                .with(intent)
                .to(findViewById(R.id.sub_imageView))
                .interpolator(new BounceInterpolator())
                .enterListener(new SimpleAnimatorListener() {
                    @Override
                    public void onAnimationStart(Animator animation) {
                        Log.e("TAG", "onEnterAnimationStart: ");
                    }

                    @Override
                    public void onAnimationEnd(Animator animation) {
                        Log.e("TAG", "onEnterAnimationEnd: ");
                    }

                })
                .start(savedInstanceState)
                .exitListener(new SimpleAnimatorListener() {
                    @Override
                    public void onAnimationStart(Animator animation) {
                        Log.e("TAG", "onOutAnimationStart: ");
                    }

                    @Override
                    public void onAnimationEnd(Animator animation) {
                        Log.e("TAG", "onOutAnimationEnd: ");
                    }
                });

2016-10-08 09:46 UTC, takahirom commented
👀

2016-10-08 12:31 UTC, takahirom commented
I fixed ci build.
Can you rebase master?

Like this

```
 git pull --rebase git@github.com:takahirom/PreLollipopTransition.git master
```

2016-10-08 13:54 UTC, takahirom requested changes
Sorry. Please change dependency for ci build.

https://github.com/takahirom/PreLollipopTransition/blob/master/sample-app/build.gradle#L67

``` groovy
    compile project(":pre-lollipop-activity-transition")

//    compile('com.kogitune:pre-lollipop-activity-transition:1.3.2') {
//        exclude module: 'support-v4'
//    }
```

2016-10-08 14:05 UTC, lovejjfg commented
Should i change to use this` compile project(":pre-lollipop-activity-transition")`?   before i commit  ,there is used the following dependency...

2016-10-08 14:10 UTC, takahirom commented
@lovejjfg 
Yes.. It is my mistake. Sorry. 🙇 
I want to confirm ci build.

2016-10-08 14:13 UTC, takahirom approved these changes

2016-10-08 14:36 UTC, takahirom requested changes
Please modify some code. if you have question please let me know

2016-10-08 14:36 UTC, takahirom commented on pre-lollipop-activity-transition/src/main/java/com/kogitune/activity_transition/SimpleAnimatorListener.java
> +public abstract class SimpleAnimatorListener implements Animator.AnimatorListener {
Probably you can use AnimatorListenerAdapter.
https://developer.android.com/reference/android/animation/AnimatorListenerAdapter.html

2016-10-08 14:36 UTC, takahirom commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/support_fragment/SupportStartFragment.java
> +                FragmentTransitionLauncher
Thank you for readable code! 👍

2016-10-08 14:36 UTC, takahirom commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/SubActivity.java
> +                .exitListener(new Animator.AnimatorListener() {
Probably If you split code, code become more readable.

```java
        exitTransition = ActivityTransition
                .with(getIntent())
                .enterListener(new SimpleAnimatorListener() {
                    @Override
                    public void onAnimationEnd(Animator animation) {
                        Log.e("TAG", "onEnterAnimationEnd");
                    }

                    @Override
                    public void onAnimationStart(Animator animation) {
                        Log.e("TAG", "onOEnterAnimationStart ");
                    }
                })
                .to(findViewById(R.id.sub_imageView))
                .start(savedInstanceState);

       exitTransition.exitListener(new Animator.AnimatorListener() {
                    @Override
                    public void onAnimationStart(Animator animation) {
                        Log.e("TAG", "onOutAnimationStart: ");
                    }

                    @Override
                    public void onAnimationEnd(Animator animation) {
                        Log.e("TAG", "onOutAnimationEnd: ");
                    }

                    @Override
                    public void onAnimationCancel(Animator animation) {

                    }

                    @Override
                    public void onAnimationRepeat(Animator animation) {

                    }
                });
```

2016-10-08 14:43 UTC, lovejjfg commented on pre-lollipop-activity-transition/src/main/java/com/kogitune/activity_transition/SimpleAnimatorListener.java
> +public abstract class SimpleAnimatorListener implements Animator.AnimatorListener {
oh It's my fault...

2016-10-08 15:37 UTC, takahirom approved these changes

2016-10-08 15:38 UTC, merged

2016-10-08 15:38 UTC, takahirom commented
Merged

2016-11-26 02:03 UTC, thanhbinh84 commented
the version 1.3.2 doesn't include this code. could you add a new release for this. Thanks.