fix setArguments method
takahirom/PreLollipopTransition pull request #42
Opened 2016-11-25 04:48 UTC by lovejjfg

fixed if customer also need to call setArguments() then the bundle will be overwritten by the latest..

2016-11-26 02:44 UTC, takahirom commented
Thanks!!
I will look this in this weekend

2016-11-26 07:28 UTC, takahirom commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:2.2.2'
👍

2016-11-26 07:58 UTC, takahirom commented
You should implement android.app.Fragment setArgument implementation.
https://github.com/takahirom/PreLollipopTransition/blob/bc0088f9fc9ef02a38e6d20fc08ef68a0fe68628/pre-lollipop-activity-transition/src/main/java/com/kogitune/activity_transition/fragment/FragmentTransitionLauncher.java#L58-L58

I confirmed it in sample app.

```java
FATAL EXCEPTION: main
Process: com.kogitune.prelollipoptransition, PID: 29208
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.os.Bundle.getInt(java.lang.String)' on a null object reference
at com.kogitune.activity_transition.core.TransitionData.<init>(TransitionData.java:50)
at com.kogitune.activity_transition.core.TransitionAnimation.startAnimation(TransitionAnimation.java:43)
at com.kogitune.activity_transition.fragment.FragmentTransition.start(FragmentTransition.java:96)
at com.kogitune.prelollipoptransition.fragment.EndFragment.onCreateView(EndFragment.java:46)
at android.app.Fragment.performCreateView(Fragment.java:2353)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:995)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
at android.app.BackStackRecord.run(BackStackRecord.java:816)
at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1578)
at android.app.FragmentManagerImpl$1.run(FragmentManager.java:483)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

2016-11-26 08:46 UTC, lovejjfg commented
@takahirom  I guess I forget update all `prepare()` methods..

2016-11-26 08:55 UTC, takahirom commented
Thanks! I will look.

2016-11-26 12:16 UTC, takahirom requested changes
Thank you for pull request!
Please check instrumentation test.

2016-11-26 12:16 UTC, takahirom commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/fragment/ListViewFragment.java
> +package com.kogitune.prelollipoptransition.fragment;
Please add license

2016-11-26 12:16 UTC, takahirom commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/ListViewActivity.java
> +                        Log.d("TAG", "onOEnterAnimationStart!!");
onOEnterAnimationStart -> onEnterAnimationStart

2016-11-26 12:16 UTC, takahirom commented on pre-lollipop-activity-transition/src/main/java/com/kogitune/activity_transition/fragment/FragmentTransitionLauncher.java
Please add same comment.

```
You should call this method after init your argumentsBundle.otherwise the transitionBundle will be not work.
```

2016-11-26 12:16 UTC, takahirom commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/ListViewActivity.java
>  public class ListViewActivity extends AppCompatActivity {
Please run instrumentation test.
Sorry for no test on ci (I want to fix it..)

You can do instrumentation test like this.
![image](https://cloud.githubusercontent.com/assets/1386930/20640277/b3ea4c16-b41c-11e6-9bed-8f8d288c110e.png)

2016-11-26 12:16 UTC, takahirom commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/MainActivity.java
> +                //init your bundle first!!
Thank you for comment!

2016-11-26 14:54 UTC, lovejjfg commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/ListViewActivity.java
>  public class ListViewActivity extends AppCompatActivity {
passed

2016-11-26 14:55 UTC, lovejjfg commented on sample-app/src/main/java/com/kogitune/prelollipoptransition/ListViewActivity.java
> +                        Log.d("TAG", "onOEnterAnimationStart!!");
0.0

2016-11-29 12:52 UTC, merged

2016-12-11 07:56 UTC, takahirom commented
May I add you to the contributor list of README?

2016-12-11 08:14 UTC, lovejjfg commented
My pleasure ,thanks.

2016-12-11 08:20 UTC, takahirom commented
Added 🎉 
https://github.com/takahirom/PreLollipopTransition/commit/6bf62130f204d1255e4e589327b1ce42f7603350